# Permisos de edificación
descripción: Permisos de edificación capitales regionales, provinciales y urbanos de 50 mil habitantes.
sitio web: http://geoine-ine-chile.opendata.arcgis.com/search?q=permisos
hecho a partir de la concatenación de archivos anuales y el primer semestre de 2018.

In [1]:
# librerías GENERALES
import os
import pandas as pd
#from escalas_ecvu import * # sólo para caso específico ECVU
import matplotlib.pyplot as plt
import seaborn as sns
import dateutil, datetime # para trabajar con fechas

# funciones externas personales
# from funciones import * # Análisis estadístico y agregaciones
# from grafica import *

# librerías ESPECÍFICAS CUADERNO
#from escalas_ecvu import * # sólo para caso específico ECVU

In [2]:
DATA = '/Users/ignacioabe/personal/trabajos/ciencia de datos/jupyterlab/datos'

In [3]:
# Lectura fuentes de datos: MICRODATOS CENSO 2017
df = pd.read_csv(os.path.join(DATA, 'Chile', 'permisos_2010-2018.csv'))
print(df.shape)
#df.set_index('COD_MANZANA', inplace=True)

(98825, 18)

/Users/ignacioabe/.venv/jlab/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3062: DtypeWarning: Columns (13,15,16) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [4]:
df.iloc[0]

X                             -70.3205
Y                             -26.4218
OBJECTID                          1001
ID                        320120100012
COD_REGION                           3
GLOSA_REGI           Región de Atacama
COD_COMUNA                        3201
GLOSA_COMU                    Chañaral
AGNO                              2010
CANTIDAD_U                           1
USO_DESTIN                HABITACIONAL
NUM_PISOS                            1
SUPERFICIE                          55
LOCALIZACI                         SII
FECHA_PE      2010-11-01T00:00:00.000Z
PRECISION                          NaN
FUENTE_GEO                         NaN
GLOSA_DEST                Casa aislada
Name: 0, dtype: object

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98825 entries, 0 to 98824
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   X           98825 non-null  float64
 1   Y           98825 non-null  float64
 2   OBJECTID    98825 non-null  int64
 3   ID          98825 non-null  int64
 4   COD_REGION  98825 non-null  int64
 5   GLOSA_REGI  98825 non-null  object
 6   COD_COMUNA  98825 non-null  int64
 7   GLOSA_COMU  98825 non-null  object
 8   AGNO        98825 non-null  int64
 9   CANTIDAD_U  98825 non-null  int64
 10  USO_DESTIN  98825 non-null  object
 11  NUM_PISOS   98825 non-null  int64
 12  SUPERFICIE  98825 non-null  int64
 13  LOCALIZACI  92080 non-null  object
 14  FECHA_PE    98825 non-null  object
 15  PRECISION   6745 non-null   object
 16  FUENTE_GEO  6745 non-null   object
 17  GLOSA_DEST  98825 non-null  object
dtypes: float64(2), int64(8), object(8)
memory usage: 13.6+ MB

In [6]:
df.sample()

,X,Y,OBJECTID,ID,COD_REGION,GLOSA_REGI,COD_COMUNA,GLOSA_COMU,AGNO,CANTIDAD_U,USO_DESTIN,NUM_PISOS,SUPERFICIE,LOCALIZACI,FECHA_PE,PRECISION,FUENTE_GEO,GLOSA_DEST
54547,-71.428879,-33.044705,2985,580120150154,5,Región de Valparaíso,5801,Quilpué,2015,1,HABITACIONAL,1,50,RANGE_INTERPOLATED,2015-12-01T00:00:00.000Z,NaN,NaN,Casa aislada

In [7]:
df.set_index('ID')

,X,Y,OBJECTID,COD_REGION,GLOSA_REGI,COD_COMUNA,GLOSA_COMU,AGNO,CANTIDAD_U,USO_DESTIN,NUM_PISOS,SUPERFICIE,LOCALIZACI,FECHA_PE,PRECISION,FUENTE_GEO,GLOSA_DEST
ID,,,,,,,,,,,,,,,,,
320120100012,-70.320479,-26.421776,1001,3,Región de Atacama,3201,Chañaral,2010,1,HABITACIONAL,1,55,SII,2010-11-01T00:00:00.000Z,NaN,NaN,Casa aislada
320120100083,-70.325209,-26.555475,1002,3,Región de Atacama,3201,Chañaral,2010,1,NO HABITACIONAL,1,169,SII,2010-12-01T00:00:00.000Z,NaN,NaN,Industria
330120100005,-70.712612,-28.618617,1003,3,Región de Atacama,3301,Vallenar,2010,1,HABITACIONAL,1,59,SII,2010-01-01T00:00:00.000Z,NaN,NaN,Casa aislada
320120100045,-70.609720,-26.334518,1004,3,Región de Atacama,3201,Chañaral,2010,1,HABITACIONAL,1,55,SII,2010-11-01T00:00:00.000Z,NaN,NaN,Casa aislada
320120100060,-70.610246,-26.334841,1005,3,Región de Atacama,3201,Chañaral,2010,1,HABITACIONAL,1,55,SII,2010-11-01T00:00:00.000Z,NaN,NaN,Casa aislada
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1410120180230,-73.241014,-39.775594,6741,14,REGIÓN DE LOS RÍOS,14101,Valdivia,2018,2,HABITACIONAL,1,90,NaN,2018-04-01T00:00:00.000Z,ALTA,SII,Casa aislada
1410120180335,-73.227955,-39.840074,6742,14,REGIÓN DE LOS RÍOS,14101,Valdivia,2018,1,HABITACIONAL,2,33,NaN,2018-06-01T00:00:00.000Z,ALTA,SII,Casa pareada
1610120180060,-72.081522,-36.599028,6743,16,REGIÓN DE ÑUBLE,16101,Chillán,2018,1,HABITACIONAL,1,56,NaN,2018-03-01T00:00:00.000Z,ALTA,SII,Casa aislada
1610220180035,-72.298871,-36.745836,6744,16,REGIÓN DE ÑUBLE,16102,Bulnes,2018,1,NO HABITACIONAL,2,825,NaN,2018-02-01T00:00:00.000Z,ALTA,OTRAS FUENTES,"Jardines infantiles, parvularios"
1620120180009,-72.541958,-36.276441,6745,16,REGIÓN DE ÑUBLE,16201,Quirihue,2018,1,NO HABITACIONAL,1,51,NaN,2018-02-01T00:00:00.000Z,ALTA,OTRAS FUENTES,Comercio

In [8]:
len(df.groupby('GLOSA_COMU')['COD_COMUNA'].value_counts())
# 125 comunas registran permisos, según el censo Chile tiene 346.

125

In [9]:
# Tabla proyectos por clasificación
tabla = df.groupby('USO_DESTIN').agg({'SUPERFICIE': ['sum'], 'CANTIDAD_U': ['sum'], 'NUM_PISOS': ['sum', 'count']})
#tabla.sort_values([('SUPERFICIE', 'sum')], ascending=False, inplace=True)
print(tabla)
#tabla.to_csv(os.path.join(output_f, 'clasificacion.csv'))

                SUPERFICIE CANTIDAD_U NUM_PISOS
                       sum        sum       sum  count
USO_DESTIN
HABITACIONAL      47963208     583507    118457  71037
MIXTO             24552564     286606     18392   4469
NO HABITACIONAL   29493404      25595     39319  23319

In [11]:
# Cuál es el proyecto con el máximo de unidades?
df.loc[df['CANTIDAD_U'].idxmax()]

X                                                      -70.5494
Y                                                      -33.4981
OBJECTID                                                   6256
ID                                                1312220180027
COD_REGION                                                   13
GLOSA_REGI                     REGIÓN METROPOLITANA DE SANTIAGO
COD_COMUNA                                                13122
GLOSA_COMU                                            Peñalolén
AGNO                                                       2018
CANTIDAD_U                                                 2370
USO_DESTIN                                                MIXTO
NUM_PISOS                                                    15
SUPERFICIE                                               322547
LOCALIZACI                                                  NaN
FECHA_PE                               2018-02-01T00:00:00.000Z
PRECISION                                                  ALTA
FUENTE_GEO                                                  SII
GLOSA_DEST    Nueve edificios o bloques y más; Comercio; Per...
Name: 98335, dtype: object

In [12]:
# Y de superficie construída?
df.loc[df['SUPERFICIE'].idxmax()]

X                                     -70.8568
Y                                     -33.4513
OBJECTID                                  9385
ID                               1312420140072
COD_REGION                                  13
GLOSA_REGI    Región Metropolitana de Santiago
COD_COMUNA                               13124
GLOSA_COMU                            Pudahuel
AGNO                                      2014
CANTIDAD_U                                   1
USO_DESTIN                     NO HABITACIONAL
NUM_PISOS                                    1
SUPERFICIE                              329062
LOCALIZACI                    GEOMETRIC_CENTER
FECHA_PE              2014-09-01T00:00:00.000Z
PRECISION                                  NaN
FUENTE_GEO                                 NaN
GLOSA_DEST        Transportes y almacenamiento
Name: 49404, dtype: object

In [13]:
# Los 5 permisos con más unidades
df.sort_values('CANTIDAD_U', ascending=False).head(5)

,X,Y,OBJECTID,ID,COD_REGION,GLOSA_REGI,COD_COMUNA,GLOSA_COMU,AGNO,CANTIDAD_U,USO_DESTIN,NUM_PISOS,SUPERFICIE,LOCALIZACI,FECHA_PE,PRECISION,FUENTE_GEO,GLOSA_DEST
98335,-70.549428,-33.498111,6256,1312220180027,13,REGIÓN METROPOLITANA DE SANTIAGO,13122,Peñalolén,2018,2370,MIXTO,15,322547,NaN,2018-02-01T00:00:00.000Z,ALTA,SII,Nueve edificios o bloques y más; Comercio; Per...
13810,-73.146158,-36.957461,4514,810220110009,8,Región del BioBío,8102,Coronel,2011,2010,HABITACIONAL,2,136307,CRF - SII,2011-01-01T00:00:00.000Z,NaN,NaN,Casa aislada
15725,-72.775698,-38.761247,6429,910120110044,9,Región de la Araucanía,9101,Temuco,2011,1514,HABITACIONAL,2,77590,CRF - SII,2011-02-01T00:00:00.000Z,NaN,NaN,Casa aislada
74430,-70.676494,-33.477711,9820,1310120160078,13,Región Metropolitana de Santiago,13101,Santiago,2016,1401,MIXTO,15,67273,CRF - SII,2016-06-01T00:00:00.000Z,NaN,NaN,Cuatro edificios o bloques; Comercio
74431,-70.676494,-33.477711,9821,1310120160066,13,Región Metropolitana de Santiago,13101,Santiago,2016,1401,MIXTO,15,67314,CRF - SII,2016-06-01T00:00:00.000Z,NaN,NaN,Cuatro edificios o bloques; Locales comerciales

In [14]:
# Los 5 permisos con más superficie
df.sort_values('SUPERFICIE', ascending=False).head(5)

,X,Y,OBJECTID,ID,COD_REGION,GLOSA_REGI,COD_COMUNA,GLOSA_COMU,AGNO,CANTIDAD_U,USO_DESTIN,NUM_PISOS,SUPERFICIE,LOCALIZACI,FECHA_PE,PRECISION,FUENTE_GEO,GLOSA_DEST
49404,-70.856780,-33.451276,9385,1312420140072,13,Región Metropolitana de Santiago,13124,Pudahuel,2014,1,NO HABITACIONAL,1,329062,GEOMETRIC_CENTER,2014-09-01T00:00:00.000Z,NaN,NaN,Transportes y almacenamiento
98335,-70.549428,-33.498111,6256,1312220180027,13,REGIÓN METROPOLITANA DE SANTIAGO,13122,Peñalolén,2018,2370,MIXTO,15,322547,NaN,2018-02-01T00:00:00.000Z,ALTA,SII,Nueve edificios o bloques y más; Comercio; Per...
6163,-70.540260,-33.413756,6164,1311420100016,13,Región Metropolitana de Santiago,13114,Las Condes,2010,1,NO HABITACIONAL,3,299552,RANGE_INTERPOLATED,2010-04-01T00:00:00.000Z,NaN,NaN,Cultura
28168,-70.569086,-33.453323,7542,1311320120041,13,Región Metropolitana de Santiago,13113,La Reina,2012,2,NO HABITACIONAL,14,245051,RANGE_INTERPOLATED,2012-07-01T00:00:00.000Z,NaN,NaN,Comercio; Otros
51299,-70.654702,-33.424820,11280,1310820140061,13,Región Metropolitana de Santiago,13108,Independencia,2014,2,NO HABITACIONAL,12,233382,ROOFTOP,2014-12-01T00:00:00.000Z,NaN,NaN,Comercio; Otros

## Usos habitacionales

In [15]:
# creación de dataframe sólo para usos habitacionales
dfh = df[df['USO_DESTIN']=='HABITACIONAL']
dfh = dfh.set_index('ID')

In [16]:
# Tabla proyectos por clasificación
tabla = dfh.groupby('COD_COMUNA').agg({'SUPERFICIE': ['sum'], 'CANTIDAD_U': ['sum'], 'NUM_PISOS': ['sum', 'count']})
#tabla.sort_values([('SUPERFICIE', 'sum')], ascending=False, inplace=True)
tabla

           SUPERFICIE CANTIDAD_U NUM_PISOS
                  sum        sum       sum count
COD_COMUNA
1101           581538       5251      1109   305
1107           388700       5900      2319  1279
1401            22389        391       165   124
2101          1158750      11008      1818   567
2201           381952       5050       950   549
...               ...        ...       ...   ...
16101           52834        750       107    74
16102           21754        337        43    40
16103            2143         25        22    18
16201            4273         30        24    16
16301            1445         21        18    16

[123 rows x 4 columns]

In [17]:
tabla.columns = ["_".join(x) for x in tabla.columns.ravel()] # sacar los multi índices simplifica un montón trabajar con los datos
tabla.columns

Index(['SUPERFICIE_sum', 'CANTIDAD_U_sum', 'NUM_PISOS_sum', 'NUM_PISOS_count'], dtype='object')

In [18]:
tabla.sort_values('SUPERFICIE_sum', ascending=False)

            SUPERFICIE_sum  CANTIDAD_U_sum  NUM_PISOS_sum  NUM_PISOS_count
COD_COMUNA
13120              1928402           18469           1784              272
13101              1825321           26559           1775              271
13106              1742543           32400           2446              563
13130              1668324           21668           2045              218
13114              1417434            8127           1532              422
...                    ...             ...            ...              ...
12201                 4229              49             34               30
5201                  2952              36             39               36
16103                 2143              25             22               18
15201                 1975              35              3                3
16301                 1445              21             18               16

[123 rows x 4 columns]

In [19]:
# Tablas para usos habitacionales
tabla = dfh.groupby('COD_REGION').agg({'SUPERFICIE': ['mean'], 'CANTIDAD_U': ['mean'], 'NUM_PISOS': ['mean', 'count']})
tabla['num_permisos'] = tabla['NUM_PISOS']['count']
tabla.drop([('NUM_PISOS','count')], axis=1, inplace=True)
tabla['sup_promedio'] = tabla['SUPERFICIE']['mean'] / tabla['CANTIDAD_U']['mean']
#tabla.to_csv(os.path.join(output_f, 'clasificacion.csv'))
print(tabla)

             SUPERFICIE CANTIDAD_U NUM_PISOS num_permisos sup_promedio
                   mean       mean      mean
COD_REGION
1            581.163349   6.757611  2.103630         1708    86.001300
2            949.751020  10.181341  2.128280         1715    93.283489
3            370.617582   5.416850  1.299634         1365    68.419394
4            888.206297  12.017091  1.599700         3335    73.911920
5            643.299769   7.468358  1.899949         7806    86.136711
6            479.221479   6.155157  1.292972         3287    77.856910
7            328.897897   4.330266  1.224219         6846    75.953280
8            401.674271   5.542521  1.459067        13852    72.471403
9            352.606964   4.760827  1.337106         4595    74.064226
10           481.672276   6.181872  1.646590         3387    77.916898
11           185.139430   2.507496  1.436282         1334    73.834380
12           206.052658   2.539619  1.343531         1994    81.135269
13          1321.312478  15.058376  2.093200        16942    87.746017
14           328.477571   4.420480  1.613049         2207    74.308118
15           717.396000   9.644000  1.758000          500    74.387806
16           502.737805   7.091463  1.304878          164    70.893379

## Restringe análisis aún más, a la Región Metropolitana

In [20]:
dfhr = dfh[dfh['COD_REGION'] == 13]
dfhr.head()

,X,Y,OBJECTID,COD_REGION,GLOSA_REGI,COD_COMUNA,GLOSA_COMU,AGNO,CANTIDAD_U,USO_DESTIN,NUM_PISOS,SUPERFICIE,LOCALIZACI,FECHA_PE,PRECISION,FUENTE_GEO,GLOSA_DEST
ID,,,,,,,,,,,,,,,,,
1350120100037,-71.216684,-33.686159,5714,13,Región Metropolitana de Santiago,13501,Melipilla,2010,1,HABITACIONAL,1,45,APPROXIMATE,2010-04-01T00:00:00.000Z,NaN,NaN,Casa pareada
1350120100006,-71.216684,-33.686159,5715,13,Región Metropolitana de Santiago,13501,Melipilla,2010,1,HABITACIONAL,1,45,APPROXIMATE,2010-01-01T00:00:00.000Z,NaN,NaN,Casa pareada
1350120100008,-71.216684,-33.686159,5716,13,Región Metropolitana de Santiago,13501,Melipilla,2010,1,HABITACIONAL,1,45,APPROXIMATE,2010-01-01T00:00:00.000Z,NaN,NaN,Casa pareada
1360120100025,-70.927394,-33.663747,5717,13,Región Metropolitana de Santiago,13601,Talagante,2010,1,HABITACIONAL,1,243,APPROXIMATE,2010-06-01T00:00:00.000Z,NaN,NaN,Casa aislada
1340220100027,-70.722762,-33.731726,5718,13,Región Metropolitana de Santiago,13402,Buin,2010,97,HABITACIONAL,2,7385,CRF,2010-09-01T00:00:00.000Z,NaN,NaN,Casa aislada

In [21]:
# Tablas para usos habitacionales
tabla = dfhr.groupby('GLOSA_COMU').agg({'SUPERFICIE': ['mean'], 'CANTIDAD_U': ['mean'], 'NUM_PISOS': ['mean', 'count']})
tabla['num_permisos'] = tabla['NUM_PISOS']['count']
tabla.drop([('NUM_PISOS','count')], axis=1, inplace=True)
tabla['sup_promedio'] = tabla['SUPERFICIE']['mean'] / tabla['CANTIDAD_U']['mean']
# tabla.to_csv(os.path.join(output_f, 'clasificacion.csv'))
# tabla['GLOSA_COMU'] = dic[tabla.index]
tabla.sort_values('sup_promedio')

,SUPERFICIE,CANTIDAD_U,NUM_PISOS,num_permisos,sup_promedio
,mean,mean,mean,,
GLOSA_COMU,,,,,
Estación Central,3095.103020,57.548845,4.344583,563,53.782191
Independencia,3387.638158,62.322368,4.407895,152,54.356698
La Pintana,306.789683,5.488095,1.293651,252,55.900940
Quinta Normal,3417.558282,59.785276,4.239264,163,57.163879
Lo Espejo,59.829060,1.000000,1.085470,117,59.829060
La Granja,458.423810,7.471429,1.395238,210,61.356915
La Cisterna,1279.637470,20.145985,2.350365,411,63.518237
Renca,290.200340,4.543294,1.258065,589,63.874439
El Bosque,294.313409,4.492730,1.218094,619,65.508810
Lampa,1196.722798,17.567358,1.204663,386,68.121958
San Bernardo,583.842014,8.569444,1.342014,576,68.130673
San Joaquín,1279.651685,18.775281,2.337079,89,68.156194
Conchalí,324.137203,4.746702,1.372032,379,68.286826
Padre Hurtado,1252.310000,18.230000,1.335000,200,68.695008
Santiago,6735.501845,98.003690,6.549815,271,68.727023
Quilicura,1595.540541,22.756757,1.832432,185,70.112827
Pedro Aguirre Cerda,72.565657,1.002525,1.151515,396,72.382872
Puente Alto,1576.790210,21.543124,1.529138,429,73.192274
Melipilla,241.479197,3.269727,1.186514,697,73.853006
Cerro Navia,145.890983,1.947510,1.253028,743,74.911541
Pudahuel,674.500000,8.994872,1.825641,390,74.987172
San Ramón,91.257996,1.211087,1.215352,469,75.352113
San Miguel,7652.862385,99.394495,9.380734,218,76.994831
La Florida,1549.430836,19.930836,2.367435,694,77.740385
Buin,1238.373096,15.596447,1.398477,394,79.400976
Maipú,907.272973,11.118919,1.567568,370,81.597229
Paine,322.136905,3.857143,1.220238,168,83.516975
Recoleta,437.542274,5.227405,1.647230,343,83.701617
Macul,3409.094241,39.429319,3.905759,191,86.460895
Cerrillos,524.251908,5.965649,1.511450,262,87.878439
Lo Prado,119.540773,1.261803,1.351931,233,94.738095
Peñaflor,428.388889,4.501736,1.343750,576,95.160818
Ñuñoa,7089.713235,67.900735,6.558824,272,104.412908
Talagante,368.240741,3.384259,1.319444,216,108.809850
San José de Maipo,148.658228,1.360759,1.373418,158,109.246512
Huechuraba,1976.813008,15.934959,1.569106,246,124.055102
Peñalolén,996.253597,7.138489,1.631295,556,139.560847
Colina,671.197960,4.478704,1.620876,1667,149.864318
Providencia,4975.728571,32.864286,6.285714,140,151.402304
La Reina,1017.088146,6.574468,2.164134,329,154.702728
Las Condes,3358.848341,19.258294,3.630332,422,174.410484
Pirque,212.634241,1.050584,1.264591,257,202.396296
Lo Barnechea,2008.031294,8.460882,2.266003,703,237.331204
Vitacura,3642.547718,14.904564,3.348548,241,244.391425

In [22]:
# Total de unidades por comuna y año
tabla = dfhr.groupby(['GLOSA_COMU', pd.DatetimeIndex(dfhr['FECHA_PE']).year])['CANTIDAD_U'].sum().unstack()
tabla

FECHA_PE,2010,2011,2012,2013,2014,2015,2016,2017,2018
GLOSA_COMU,,,,,,,,,
Buin,135.0,751.0,867.0,1350.0,1311.0,772.0,551.0,334.0,74.0
Cerrillos,338.0,262.0,234.0,6.0,326.0,369.0,14.0,12.0,2.0
Cerro Navia,154.0,27.0,39.0,73.0,736.0,83.0,155.0,120.0,60.0
Colina,836.0,687.0,1174.0,447.0,1183.0,1595.0,557.0,873.0,114.0
Conchalí,104.0,261.0,83.0,30.0,1035.0,115.0,68.0,95.0,8.0
El Bosque,440.0,502.0,17.0,52.0,344.0,196.0,1039.0,169.0,22.0
Estación Central,335.0,190.0,1388.0,791.0,7076.0,9976.0,7503.0,4023.0,1118.0
Huechuraba,381.0,166.0,601.0,234.0,335.0,1205.0,255.0,139.0,604.0
Independencia,9.0,187.0,1292.0,5.0,2724.0,4063.0,1141.0,40.0,12.0
La Cisterna,543.0,419.0,18.0,212.0,901.0,769.0,342.0,2314.0,2762.0
La Florida,418.0,578.0,595.0,580.0,1933.0,2325.0,2148.0,2374.0,2881.0
La Granja,47.0,489.0,8.0,24.0,10.0,301.0,308.0,367.0,15.0
La Pintana,1087.0,2.0,31.0,5.0,11.0,47.0,54.0,103.0,43.0
La Reina,118.0,235.0,162.0,215.0,169.0,623.0,235.0,333.0,73.0
Lampa,91.0,928.0,716.0,208.0,1039.0,1841.0,205.0,1684.0,69.0
Las Condes,148.0,109.0,86.0,570.0,2574.0,2941.0,791.0,710.0,198.0
Lo Barnechea,300.0,218.0,396.0,489.0,1192.0,1853.0,567.0,615.0,318.0
Lo Espejo,1.0,45.0,6.0,4.0,1.0,35.0,24.0,NaN,1.0
Lo Prado,4.0,15.0,8.0,7.0,8.0,81.0,53.0,56.0,62.0
Macul,12.0,53.0,12.0,224.0,2303.0,858.0,1666.0,603.0,1800.0
Maipú,436.0,586.0,765.0,451.0,747.0,197.0,282.0,642.0,8.0
Melipilla,836.0,286.0,56.0,219.0,42.0,183.0,342.0,283.0,32.0
Padre Hurtado,398.0,296.0,342.0,359.0,1006.0,550.0,93.0,343.0,259.0
Paine,15.0,46.0,14.0,438.0,8.0,37.0,24.0,42.0,24.0
Pedro Aguirre Cerda,69.0,41.0,75.0,41.0,68.0,33.0,34.0,21.0,15.0
Peñaflor,258.0,222.0,424.0,101.0,336.0,793.0,158.0,290.0,11.0
Peñalolén,50.0,574.0,280.0,107.0,654.0,509.0,742.0,232.0,821.0
Pirque,10.0,5.0,5.0,9.0,6.0,7.0,114.0,81.0,33.0
Providencia,4.0,12.0,NaN,435.0,1162.0,1492.0,753.0,458.0,285.0
Pudahuel,158.0,690.0,105.0,479.0,635.0,702.0,85.0,627.0,27.0
Puente Alto,2231.0,1541.0,1237.0,654.0,1611.0,850.0,583.0,520.0,15.0
Quilicura,992.0,511.0,1487.0,708.0,231.0,29.0,96.0,10.0,146.0
Quinta Normal,343.0,818.0,29.0,1398.0,258.0,3726.0,2505.0,223.0,445.0
Recoleta,31.0,85.0,13.0,8.0,228.0,299.0,450.0,427.0,252.0
Renca,610.0,664.0,424.0,174.0,26.0,401.0,55.0,319.0,3.0
San Bernardo,237.0,182.0,824.0,92.0,711.0,1359.0,562.0,927.0,42.0
San Joaquín,5.0,6.0,7.0,424.0,19.0,666.0,526.0,5.0,13.0
San José de Maipo,60.0,14.0,15.0,17.0,12.0,12.0,33.0,41.0,11.0
San Miguel,7.0,23.0,15.0,1430.0,3957.0,4760.0,5935.0,5279.0,262.0
San Ramón,145.0,11.0,24.0,40.0,36.0,93.0,103.0,47.0,69.0
Santiago,124.0,171.0,112.0,2930.0,9675.0,4017.0,2378.0,5413.0,1739.0
Talagante,6.0,289.0,16.0,10.0,278.0,8.0,29.0,69.0,26.0
Vitacura,25.0,28.0,23.0,875.0,950.0,590.0,571.0,470.0,60.0
Ñuñoa,10.0,44.0,43.0,741.0,2289.0,5118.0,2670.0,5378.0,2176.0

In [23]:
# Promedio de pisos por región y año
tabla = dfhr.groupby(['GLOSA_COMU' , pd.DatetimeIndex(dfhr['FECHA_PE']).year])['NUM_PISOS'].mean().sort_values().unstack()
tabla

FECHA_PE,2010,2011,2012,2013,2014,2015,2016,2017,2018
GLOSA_COMU,,,,,,,,,
Buin,1.360000,1.363636,1.480000,1.375000,1.290598,1.473684,1.387097,1.459459,1.866667
Cerrillos,1.173077,1.893617,1.863636,1.000000,1.073171,1.421053,1.428571,1.416667,1.000000
Cerro Navia,1.058442,1.259259,1.282051,1.397260,1.418367,1.301205,1.270270,1.229508,1.200000
Colina,1.602094,1.675497,1.712329,1.619565,1.683871,1.607143,1.550459,1.593284,1.539823
Conchalí,2.375000,1.521739,1.312500,1.400000,1.531250,1.293578,1.177419,1.222222,1.125000
El Bosque,1.076923,1.111111,1.294118,1.310345,1.176471,1.472222,1.487179,1.274194,1.333333
Estación Central,1.289655,1.268293,3.000000,3.250000,7.016949,8.162162,5.032520,6.285714,3.782609
Huechuraba,1.095238,2.000000,1.478261,3.000000,2.571429,5.500000,1.227273,1.142857,2.636364
Independencia,1.555556,5.250000,9.250000,1.400000,12.000000,9.423077,3.076923,1.325000,1.416667
La Cisterna,1.588235,2.222222,1.500000,2.222222,2.461538,1.604651,1.833333,2.659574,4.440000
La Florida,1.228070,1.780000,1.755102,1.527778,3.164384,2.888889,2.404959,3.541667,3.281690
La Granja,1.021277,1.162791,1.125000,1.083333,1.666667,1.454545,2.090909,2.173913,1.466667
La Pintana,1.127273,2.000000,1.500000,1.600000,1.545455,1.148936,1.315789,1.272727,1.534884
La Reina,1.730769,2.022222,1.961538,2.095238,1.918919,2.730769,2.195122,2.727273,1.916667
Lampa,1.010989,1.230769,1.555556,1.235294,1.100000,1.388889,1.186441,1.542857,1.300000
Las Condes,2.195652,2.085106,2.042553,3.054545,5.722222,5.485294,4.000000,3.595745,3.300000
Lo Barnechea,1.942857,1.979798,2.009709,2.269231,2.743243,2.701031,2.325000,2.163636,2.276596
Lo Espejo,1.000000,1.088889,1.500000,1.250000,2.000000,1.028571,1.000000,NaN,1.000000
Lo Prado,1.750000,1.133333,1.500000,1.142857,1.500000,1.500000,1.433962,1.446429,1.161290
Macul,1.750000,2.250000,1.600000,4.625000,5.218750,6.333333,3.428571,3.000000,5.937500
Maipú,1.625000,1.522388,1.687500,1.512195,1.681818,1.473684,1.405405,2.400000,1.375000
Melipilla,1.028090,1.216561,1.518519,1.391304,1.416667,1.241379,1.183673,1.159091,1.218750
Padre Hurtado,1.411765,1.032258,1.272727,1.375000,1.666667,2.142857,1.294118,1.230769,1.277778
Paine,1.300000,1.047619,1.000000,1.300000,1.285714,1.636364,1.111111,1.294118,1.333333
Pedro Aguirre Cerda,1.043478,1.097561,1.093333,1.150000,1.235294,1.303030,1.264706,1.190476,1.066667
Peñaflor,1.388889,1.400000,1.460000,1.333333,1.250000,1.359712,1.354839,1.482759,1.000000
Peñalolén,1.937500,1.378788,1.280899,1.500000,1.700000,1.819277,1.844828,2.000000,1.453125
Pirque,1.400000,1.000000,1.200000,1.333333,1.166667,1.428571,1.268519,1.250000,1.258065
Providencia,1.750000,3.250000,NaN,5.642857,6.878788,7.088235,6.500000,6.642857,4.923077
Pudahuel,1.625000,2.461538,1.657895,1.700000,2.069767,2.878788,1.435294,2.018182,1.480000
Puente Alto,1.493243,1.794118,1.904762,1.550000,1.515152,1.633333,1.443038,1.448980,1.266667
Quilicura,2.185185,3.833333,2.296296,1.736842,1.428571,1.965517,1.303030,1.400000,1.407407
Quinta Normal,2.190476,3.647059,1.551724,4.466667,3.545455,9.666667,6.473684,1.857143,6.333333
Recoleta,1.233333,1.428571,1.307692,1.625000,2.562500,1.714286,2.344828,1.645161,1.235294
Renca,1.102564,1.154362,1.687500,1.241379,1.192308,1.448718,1.137255,1.425000,1.333333
San Bernardo,1.072464,1.210526,1.611111,1.280000,1.408163,1.242424,1.560000,1.411765,1.541667
San Joaquín,1.500000,1.200000,1.600000,2.400000,1.263158,5.700000,4.625000,1.400000,1.153846
San José de Maipo,1.500000,1.307692,1.466667,1.294118,1.600000,1.500000,1.258065,1.333333,1.454545
San Miguel,1.500000,1.727273,1.666667,9.769231,11.484848,15.090909,13.750000,8.363636,2.062500
San Ramón,1.013793,1.363636,1.375000,1.450000,1.361111,1.172043,1.388889,1.239130,1.350000
Santiago,2.428571,2.866667,2.166667,5.631579,10.884615,5.869565,5.558824,7.975000,5.619048
Talagante,1.166667,1.411765,1.125000,1.300000,1.375000,1.125000,1.275862,1.296875,1.480000
Vitacura,1.923077,1.800000,2.095238,3.794118,5.108108,4.225000,2.750000,3.205882,2.384615
Ñuñoa,2.000000,2.083333,2.400000,8.571429,8.129032,7.790323,5.687500,6.450704,7.444444

In [24]:
# Máximo de pisos por región y año
tabla = dfhr.groupby(['GLOSA_COMU' , pd.DatetimeIndex(dfhr['FECHA_PE']).year])['NUM_PISOS'].max().sort_values().unstack()
tabla

FECHA_PE             2010  2011  2012  2013  2014  2015  2016  2017  2018
GLOSA_COMU
Buin                  2.0   2.0   2.0   2.0   2.0   2.0   3.0   2.0   2.0
Cerrillos             4.0   2.0   2.0   1.0   2.0   3.0   2.0   2.0   1.0
Cerro Navia           2.0   2.0   2.0   2.0   4.0   2.0   3.0   5.0   2.0
Colina                2.0   3.0   3.0   6.0   3.0   2.0   2.0   4.0   3.0
Conchalí              5.0   5.0   2.0   2.0  24.0   3.0   4.0   2.0   2.0
El Bosque             5.0   5.0   2.0   2.0   5.0   5.0   5.0   5.0   2.0
Estación Central      4.0   4.0  23.0  23.0  31.0  38.0  35.0  27.0  24.0
Huechuraba            4.0   3.0   2.0  11.0   4.0  21.0   3.0   3.0  10.0
Independencia         2.0  16.0  18.0   2.0  23.0  25.0  23.0   2.0   2.0
La Cisterna           5.0   9.0   2.0  13.0  16.0  18.0  17.0  19.0  26.0
La Florida            5.0  13.0   5.0   5.0  20.0  18.0  26.0  20.0  22.0
La Granja             2.0   5.0   2.0   2.0   2.0   5.0  14.0  17.0   2.0
La Pintana            4.0   2.0   2.0   2.0   2.0   2.0   2.0   2.0   2.0
La Reina              4.0   4.0   3.0  11.0   2.0  18.0   9.0  15.0   4.0
Lampa                 2.0   4.0   2.0   3.0   2.0   4.0   2.0   4.0   2.0
Las Condes            8.0   3.0   3.0  13.0  15.0  18.0  14.0  15.0  15.0
Lo Barnechea          3.0   6.0   3.0   8.0   8.0  15.0   6.0   6.0  10.0
Lo Espejo             1.0   2.0   2.0   2.0   2.0   2.0   1.0   NaN   1.0
Lo Prado              2.0   2.0   2.0   2.0   2.0   5.0   3.0   2.0   2.0
Macul                 2.0   3.0   2.0  18.0  23.0  19.0  25.0  25.0  25.0
Maipú                 3.0   2.0   3.0   2.0   4.0   4.0   2.0  15.0   2.0
Melipilla             2.0   2.0   4.0   2.0   2.0   2.0   2.0   2.0   2.0
Padre Hurtado         2.0   2.0   2.0   2.0   2.0   4.0   2.0   2.0   2.0
Paine                 2.0   2.0   1.0   2.0   2.0   3.0   2.0   2.0   2.0
Pedro Aguirre Cerda   2.0   2.0   2.0   2.0   2.0   2.0   2.0   2.0   2.0
Peñaflor              2.0   2.0   2.0   2.0   2.0   3.0   2.0   3.0   1.0
Peñalolén             2.0   4.0   3.0   7.0  12.0  15.0  10.0  10.0   7.0
Pirque                2.0   1.0   2.0   3.0   2.0   2.0   2.0   2.0   2.0
Providencia           3.0   7.0   NaN  11.0  12.0  12.0  12.0  12.0  12.0
Pudahuel              2.0   4.0   2.0   5.0  17.0  18.0   2.0  28.0   2.0
Puente Alto           3.0   3.0   2.0   3.0   3.0   2.0   2.0   4.0   2.0
Quilicura             4.0   5.0   5.0   4.0   2.0   2.0   4.0   2.0   5.0
Quinta Normal         5.0  15.0   2.0  16.0  13.0  24.0  26.0  10.0  20.0
Recoleta              2.0   2.0   2.0   2.0  19.0   8.0  16.0  16.0   8.0
Renca                 2.0   5.0   5.0   4.0   2.0   6.0   2.0   4.0   2.0
San Bernardo          5.0   2.0   5.0   2.0   5.0   2.0  17.0  14.0   4.0
San Joaquín           2.0   2.0   2.0   5.0   2.0  25.0  23.0   2.0   2.0
San José de Maipo     2.0   2.0   3.0   2.0   3.0   2.0   2.0   2.0   2.0
San Miguel            2.0   2.0   2.0  21.0  25.0  26.0  23.0  23.0  13.0
San Ramón             2.0   2.0   2.0   2.0   2.0   2.0   2.0   2.0   5.0
Santiago              7.0  14.0   7.0  27.0  30.0  26.0  21.0  30.0  12.0
Talagante             2.0   4.0   2.0   2.0   3.0   2.0   2.0   3.0   2.0
Vitacura              3.0   3.0   3.0  10.0  23.0  18.0   8.0   8.0   5.0
Ñuñoa                 3.0   3.0   5.0  25.0  26.0  29.0  19.0  26.0  23.0